run:
  timeout: 10m
  modules-download-mode: readonly
  build-tags:
    - cgo

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 15
  govet:
    enable-all: true
    disable:
      - fieldalignment  # Can be noisy for CGO structs
  gosec:
    excludes:
      - G404  # Allow weak random in tests
      - G501  # Allow MD5 in tests (if needed for test vectors)
  staticcheck:
    checks: ["all"]

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - gosec
    - gocyclo
    - goconst
    - unparam
    - misspell
    - prealloc
  disable:
    # (none)

issues:
  exclude-dirs:
    - cb-mpc
  exclude-rules:
    # Exclude CGO files from some checks that don't apply well
    - path: internal/cgo/
      linters:
        - gosec  # CGO has necessary unsafe operations
        - gocritic
    # Exclude everything under cb-mpc (submodule and demos)
    - path: ^cb-mpc/
      linters:
        - gofmt
        - goimports
        - gosec
        - staticcheck
        - govet
        - errcheck
        - gosimple
        - ineffassign
        - typecheck
        - unused
        - gocyclo
        - goconst
        - unparam
        - misspell
        - prealloc
        - exportloopref
    # Allow long lines in generated code
    - path: ".*\\.pb\\.go"
      linters:
        - lll
    # Test files can be more lenient
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - unparam

  # Maximum issues count per one linter
  max-issues-per-linter: 0
  # Maximum count of issues with the same text
  max-same-issues: 0