name: Lint & Security

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  analysis:
    runs-on: ubuntu-latest
    env:
      CBMPC_USE_DOCKER: "1"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run lint target
        run: make lint

      - name: Run govulncheck target
        run: make vuln

      - name: Run gosec target
        run: make sec
